import os

file_path = r'd:\aadesh\realstate\emirates-lease-flow\src\components\leases\LeaseForm.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the start of the TabsList
start_idx = -1
for i, line in enumerate(lines):
    if '<TabsList className="grid w-full grid-cols-7">' in line:
        start_idx = i
        break

if start_idx != -1:
    # Find the "{/* Basic Information Tab */}" header which should be after the corrupted part
    end_idx = -1
    for i in range(start_idx, len(lines)):
        if '{/* Basic Information Tab */}' in lines[i]:
            end_idx = i
            break
    
    if end_idx != -1:
        # Reconstruct the TabsList correctly
        new_tabs_list = [
            '            <TabsList className="grid w-full grid-cols-7">\n',
            '              <TabsTrigger value="property">Property</TabsTrigger>\n',
            '              <TabsTrigger value="basic">Basic Info</TabsTrigger>\n',
            '              <TabsTrigger value="tenant">Tenant</TabsTrigger>\n',
            '              <TabsTrigger value="financial">Financial</TabsTrigger>\n',
            '              <TabsTrigger value="pdc">PDC</TabsTrigger>\n',
            '              <TabsTrigger value="terms">Terms</TabsTrigger>\n',
            '              <TabsTrigger value="compliance">Compliance</TabsTrigger>\n',
            '            </TabsList>\n',
            '\n'
        ]
        
        # Define the Property Tab Content (since it was lost or corrupted)
        property_tab_content = [
            '            {/* Property Information Tab */}\n',
            '            <TabsContent value="property" className="space-y-6">\n',
            '              <Card>\n',
            '                <CardHeader>\n',
            '                  <CardTitle className="flex items-center gap-2">\n',
            '                    <Building2 className="h-5 w-5" />\n',
            '                    Property Information\n',
            '                  </CardTitle>\n',
            '                  <p className="text-sm text-muted-foreground">\n',
            '                    Select an existing property and unit or add new property\n',
            '                    details\n',
            '                  </p>\n',
            '                </CardHeader>\n',
            '                <CardContent className="space-y-6">\n',
            '                  {/* Property Selection */}\n',
            '                  <div>\n',
            '                    <Label htmlFor="propertySelect">Select Property</Label>\n',
            '                    <SearchableSelect\n',
            '                      value={watchedValues.property?.id || ""}\n',
            '                      onValueChange={(value) => {\n',
            '                        const property = properties.find(\n',
            '                          (p) => p.id.toString() === value,\n',
            '                        );\n',
            '                        if (property) {\n',
            '                          setSelectedProperty(property);\n',
            '                          setAvailableUnits(property.units);\n',
            '                          setSelectedUnit(null);\n',
            '                          setValue("property.name", property.name);\n',
            '                          setValue("property.id", String(property.id));\n',
            '                          setValue("property.address", property.address);\n',
            '                          const rawType = (property.buildingType || property.type || "residential").toLowerCase();\n',
            '                          # Map building types to lease types if necessary\n',
            '                          let leaseType = rawType;\n',
            '                          if ([\'apartment\', \'villa\', \'penthouse\', \'townhouse\', \'studio\', \'duplex\'].includes(rawType)) {\n',
            '                              leaseType = \'residential\';\n',
            '                          } else if ([\'office\', \'warehouse\', \'shop\'].includes(rawType)) {\n',
            '                              leaseType = \'commercial\';\n',
            '                          }\n',
            '                          \n',
            '                          setValue("property.type", leaseType as any);\n',
            '                          setValue("property.area", property.area);\n',
            '                          setValue("property.bedrooms", property.bedrooms);\n',
            '                          setValue("property.bathrooms", property.bathrooms);\n',
            '                          setValue("property.parking", property.parking);\n',
            '                        }\n',
            '                      }}\n',
            '                      disabled={mode === "edit" || loadingData}\n',
            '                      placeholder={loadingData ? "Loading properties..." : "Choose an existing property"}\n',
            '                      searchPlaceholder="Search properties..."\n',
            '                      emptyMessage="No properties found. Please add a property first."\n',
            '                      className={errors.property?.name ? "border-red-500" : ""}\n',
            '                      options={properties.map((property) => ({\n',
            '                        value: property.id.toString(),\n',
            '                        label: property.name,\n',
            '                        description: property.address,\n',
            '                      }))}\n',
            '                    />\n',
            '                    {errors.property?.name && (\n',
            '                      <p className="text-sm text-red-500 mt-1">\n',
            '                        {errors.property.name.message}\n',
            '                      </p>\n',
            '                    )}\n',
            '                  </div>\n',
            '\n',
            '                  {/* Unit Selection */}\n',
            '                  {selectedProperty && (\n',
            '                    <div>\n',
            '                      <Label htmlFor="unitSelect">Select Unit</Label>\n',
            '                      <SearchableSelect\n',
            '                        value={watchedValues.unitId || ""}\n',
            '                        onValueChange={(unitId) => {\n',
            '                          setValue("unitId", unitId);\n',
            '\n',
            '                          # Find selected unit data (you probably already do something similar)\n',
            '                          const foundUnit = availableUnits.find(\n',
            '                            (u) => String(u.id) === unitId,\n',
            '                          );\n',
            '                          if (foundUnit) {\n',
            '                            setSelectedUnit(foundUnit);\n',
            '\n',
            '                            # Update property/unit related fields (you probably have some of these already)\n',
            '                            setValue(\n',
            '                              "property.unit",\n',
            '                              foundUnit.unit || foundUnit.unitNumber || "",\n',
            '                            );\n',
            '                            setValue(\n',
            '                              "property.area",\n',
            '                              Number(foundUnit.area) || 0,\n',
            '                            );\n',
            '                            setValue(\n',
            '                              "property.bedrooms",\n',
            '                              Number(foundUnit.bedrooms) || 0,\n',
            '                            );\n',
            '                            setValue(\n',
            '                              "property.bathrooms",\n',
            '                              Number(foundUnit.bathrooms) || 0,\n',
            '                            );\n',
            '                            setValue(\n',
            '                              "property.parking",\n',
            '                              Number(foundUnit.parking || foundUnit.parkingSpaces) || 0,\n',
            '                            );\n',
            '                            setValue(\n',
            '                              "leaseDetails.monthlyRent",\n',
            '                              Number(\n',
            '                                foundUnit.monthlyRent || foundUnit.rentAmount,\n',
            '                              ) || 0,\n',
            '                            );\n',
            '                            loadUnitServices(unitId);\n',
            '                          }\n',
            '                        }}\n',
            '                        disabled={mode === "edit"}\n',
            '                        placeholder="Choose a unit"\n',
            '                        searchPlaceholder="Search units..."\n',
            '                        emptyMessage="No units available"\n',
            '                        className={errors.unitId ? "border-red-500" : ""}\n',
            '                        options={availableUnits\n',
            '                          .filter((unit) => (unit.status || \'available\').toLowerCase() !== \'occupied\' || unit.id.toString() === watchedValues.unitId)\n',
            '                          .map((unit) => ({\n',
            '                            value: unit.id.toString(),\n',
            '                            label: unit.unit,\n',
            '                            description: `${unit.area} sq ft • ${unit.bedrooms} bed • ${unit.bathrooms} bath • AED ${unit.monthlyRent?.toLocaleString()}/month`,\n',
            '                          }))}\n',
            '                      />\n',
            '                      {errors.unitId && (\n',
            '                        <p className="text-sm text-red-500 mt-1">\n',
            '                          {errors.unitId.message}\n',
            '                        </p>\n',
            '                      )}\n',
            '                    </div>\n',
            '                  )}\n',
            '\n',
            '                  <Separator />\n',
            '\n',
            '                  {/* Selected Property & Unit Display */}\n',
            '                  {selectedProperty && selectedUnit && (\n',
            '                    <div className="p-4 bg-muted/50 rounded-lg">\n',
            '                      <h4 className="font-semibold mb-3 flex items-center gap-2">\n',
            '                        <CheckCircle className="h-4 w-4 text-green-600" />\n',
            '                        Selected Property & Unit\n',
            '                      </h4>\n',
            '                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">\n',
            '                        <div>\n',
            '                          <p className="text-sm text-muted-foreground">\n',
            '                            Property\n',
            '                          </p>\n',
            '                          <p className="font-medium">{selectedProperty.title || selectedProperty.name}</p>\n',
            '                          <p className="text-sm text-muted-foreground">\n',
            '                            {selectedProperty.address || selectedProperty.location}\n',
            '                          </p>\n',
            '                        </div>\n',
            '                        <div>\n',
            '                          <p className="text-sm text-muted-foreground">Unit</p>\n',
            '                          <p className="font-medium">{selectedUnit.unit}</p>\n',
            '                          <p className="text-sm text-muted-foreground">\n',
            '                            {selectedUnit.area} sq ft • {selectedUnit.bedrooms}{\" \"}\n',
            '                            bed • {selectedUnit.bathrooms} bath\n',
            '                          </p>\n',
            '                        </div>\n',
            '                        <div>\n',
            '                          <p className="text-sm text-muted-foreground">\n',
            '                            Monthly Rent\n',
            '                          </p>\n',
            '                          <p className="font-bold text-lg text-primary">\n',
            '                            AED {(selectedUnit.monthlyRent || selectedUnit.rentAmount || selectedUnit.rent || 0).toLocaleString()}\n',
            '                          </p>\n',
            '                        </div>\n',
            '                        <div>\n',
            '                          <p className="text-sm text-muted-foreground">\n',
            '                            Parking\n',
            '                          </p>\n',
            '                          <p className="font-medium">\n',
            '                            {selectedUnit.parking || selectedUnit.parkingSpaces || 0} space(s)\n',
            '                          </p>\n',
            '\n',
            '                        </div>\n',
            '                      </div>\n',
            '                    </div>\n',
            '                  )}\n',
            '\n',
            '                  <Separator />\n',
            '\n',
            '                  {/* Manual Entry Option */}\n',
            '                  <div>\n',
            '                    {mode === "create" && <div className="flex items-center gap-2 mb-4">\n',
            '                      <Button\n',
            '                        type="button"\n',
            '                        variant="outline"\n',
            '                        size="sm"\n',
            '                        onClick={() => {\n',
            '                          # Clear property and unit selection to allow manual entry\n',
            '                          setSelectedProperty(null);\n',
            '                          setAvailableUnits([]);\n',
            '                          setSelectedUnit(null);\n',
            '                          setValue("unitId", "");\n',
            '                          setValue("property", {\n',
            '                            name: "",\n',
            '                            unit: "",\n',
            '                            address: "",\n',
            '                            type: "residential",\n',
            '                            area: 0,\n',
            '                            bedrooms: 0,\n',
            '                            bathrooms: 0,\n',
            '                            parking: 0,\n',
            '                          });\n',
            '                        }}\n',
            '                      >\n',
            '                        <Plus className="h-4 w-4 mr-2" />\n',
            '                        Add New Property\n',
            '                      </Button>\n',
            '                      <p className="text-sm text-muted-foreground">\n',
            '                        Or manually enter property details below\n',
            '                      </p>\n',
            '                    </div>}\n',
            '\n',
            '                    <div className="space-y-4">\n',
            '                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">\n',
            '                        <div>\n',
            '                          <Label htmlFor="propertyName">Property Name *</Label>\n',
            '                          <Input\n',
            '                            id="propertyName"\n',
            '                            {...register("property.name")}\n',
            '                            placeholder="Marina Heights Tower"\n',
            '                            className={\n',
            '                              errors.property?.name ? "border-red-500" : ""\n',
            '                            }\n',
            '                          />\n',
            '                          {errors.property?.name && (\n',
            '                            <p className="text-sm text-red-500 mt-1">\n',
            '                              {errors.property.name.message}\n',
            '                            </p>\n',
            '                          )}\n',
            '                        </div>\n',
            '\n',
            '                        <div>\n',
            '                          <Label htmlFor="propertyUnit">Unit Number *</Label>\n',
            '                          <Input\n',
            '                            id="propertyUnit"\n',
            '                            {...register("property.unit")}\n',
            '                            placeholder="Unit 305"\n',
            '                            className={\n',
            '                              errors.property?.unit ? "border-red-500" : ""\n',
            '                            }\n',
            '                            disabled={!!watchedValues.unitId}\n',
            '                          />\n',
            '                          {errors.property?.unit && (\n',
            '                            <p className="text-sm text-red-500 mt-1">\n',
            '                              {errors.property.unit.message}\n',
            '                            </p>\n',
            '                          )}\n',
            '                        </div>\n',
            '                      </div>\n',
            '\n',
            '                      <div>\n',
            '                        <Label htmlFor="propertyAddress">\n',
            '                          Property Address *\n',
            '                        </Label>\n',
            '                        <Textarea\n',
            '                          id="propertyAddress"\n',
            '                          {...register("property.address")}\n',
            '                          placeholder="Marina Walk, Dubai Marina, Dubai, UAE"\n',
            '                          rows={2}\n',
            '                          className={\n',
            '                            errors.property?.address ? "border-red-500" : ""\n',
            '                          }\n',
            '                        />\n',
            '                        {errors.property?.address && (\n',
            '                          <p className="text-sm text-red-500 mt-1">\n',
            '                            {errors.property.address.message}\n',
            '                          </p>\n',
            '                        )}\n',
            '                      </div>\n',
            '\n',
            '                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">\n',
            '                        <div>\n',
            '                          <Label htmlFor="propertyType">Property Type *</Label>\n',
            '                          <Select\n',
            '                            value={watchedValues.property.type}\n',
            '                            onValueChange={(value) =>\n',
            '                              setValue("property.type", value as any)\n',
            '                            }\n',
            '                          >\n',
            '                            <SelectTrigger\n',
            '                              className={\n',
            '                                errors.property?.type ? "border-red-500" : ""\n',
            '                              }\n',
            '                            >\n',
            '                              <SelectValue placeholder="Select property type" />\n',
            '                            </SelectTrigger>\n',
            '                            <SelectContent>\n',
            '                              {propertyTypes.map((type) => (\n',
            '                                <SelectItem key={type.value} value={type.value}>\n',
            '                                  <div className="flex items-center gap-2">\n',
            '                                    <type.icon className="h-4 w-4" />\n',
            '                                    {type.label}\n',
            '                                  </div>\n',
            '                                </SelectItem>\n',
            '                              ))}\n',
            '                            </SelectContent>\n',
            '                          </Select>\n',
            '                          {errors.property?.type && (\n',
            '                            <p className="text-sm text-red-500 mt-1">\n',
            '                              {errors.property.type.message}\n',
            '                            </p>\n',
            '                          )}\n',
            '                        </div>\n',
            '\n',
            '                        <div>\n',
            '                          <Label htmlFor="propertyArea">Area (sq ft) *</Label>\n',
            '                          <Input\n',
            '                            id="propertyArea"\n',
            '                            type="number"\n',
            '                            {...register("property.area", {\n',
            '                              valueAsNumber: true,\n',
            '                            })}\n',
            '                            placeholder="1200"\n',
            '                            className={\n',
            '                              errors.property?.area ? "border-red-500" : ""\n',
            '                            }\n',
            '                          />\n',
            '                          {errors.property?.area && (\n',
            '                            <p className="text-sm text-red-500 mt-1">\n',
            '                              {errors.property.area.message}\n',
            '                            </p>\n',
            '                          )}\n',
            '                        </div>\n',
            '                      </div>\n',
            '\n',
            '                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">\n',
            '                        <div>\n',
            '                          <Label htmlFor="bedrooms">Bedrooms</Label>\n',
            '                          <Input\n',
            '                            id="bedrooms"\n',
            '                            type="number"\n',
            '                            {...register("property.bedrooms", {\n',
            '                              valueAsNumber: true,\n',
            '                            })}\n',
            '                            placeholder="2"\n',
            '                          />\n',
            '                        </div>\n',
            '\n',
            '                        <div>\n',
            '                          <Label htmlFor="bathrooms">Bathrooms</Label>\n',
            '                          <Input\n',
            '                            id="bathrooms"\n',
            '                            type="number"\n',
            '                            {...register("property.bathrooms", {\n',
            '                              valueAsNumber: true,\n',
            '                            })}\n',
            '                            placeholder="2"\n',
            '                          />\n',
            '                        </div>\n',
            '\n',
            '                        <div>\n',
            '                          <Label htmlFor="parking">Parking Spaces</Label>\n',
            '                          <Input\n',
            '                            id="parking"\n',
            '                            type="number"\n',
            '                            {...register("property.parking", {\n',
            '                              valueAsNumber: true,\n',
            '                            })}\n',
            '                            placeholder="1"\n',
            '                          />\n',
            '                        </div>\n',
            '                      </div>\n',
            '                    </div>\n',
            '                  </div>\n',
            '                </CardContent>\n',
            '              </Card>\n',
            '            </TabsContent>\n',
            '\n'
        ]
        
        # Combine everything
        new_lines = lines[:start_idx] + new_tabs_list + property_tab_content + lines[end_idx:]
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
        print("Successfully fixed the file.")
    else:
        print("Could not find end index.")
else:
    print("Could not find start index.")
