const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const PrepaidExpense = sequelize.define(
  'PrepaidExpense',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    companyId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'company_id',
      references: { model: 'company_settings', key: 'id' },
    },
    prepaidNumber: { type: DataTypes.STRING(50), allowNull: false, field: 'prepaid_number' },
    categoryId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: 'category_id',
      references: { model: 'prepaid_expense_categories', key: 'id' },
    },
    description: { type: DataTypes.TEXT, allowNull: true },
    supplierId: { type: DataTypes.INTEGER, allowNull: true, field: 'supplier_id' },
    sourceType: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'MANUAL', field: 'source_type' },
    sourceDocumentId: { type: DataTypes.INTEGER, allowNull: true, field: 'source_document_id' },
    sourceDocumentNumber: { type: DataTypes.STRING(100), allowNull: true, field: 'source_document_number' },
    purchaseInvoiceId: { type: DataTypes.INTEGER, allowNull: true, field: 'purchase_invoice_id' },
    directPurchaseInvoiceId: { type: DataTypes.INTEGER, allowNull: true, field: 'direct_purchase_invoice_id' },
    paymentId: { type: DataTypes.INTEGER, allowNull: true, field: 'payment_id' },
    initialJournalVoucherId: { type: DataTypes.INTEGER, allowNull: true, field: 'initial_journal_voucher_id' },
    currencyCode: { type: DataTypes.STRING(10), allowNull: false, defaultValue: 'AED', field: 'currency_code' },
    exchangeRate: { type: DataTypes.DECIMAL(15, 6), allowNull: false, defaultValue: 1, field: 'exchange_rate' },
    totalAmount: { type: DataTypes.DECIMAL(18, 2), allowNull: false, defaultValue: 0, field: 'total_amount' },
    baseCurrencyAmount: {
      type: DataTypes.DECIMAL(18, 2),
      allowNull: false,
      defaultValue: 0,
      field: 'base_currency_amount',
    },
    serviceStartDate: { type: DataTypes.DATEONLY, allowNull: false, field: 'service_start_date' },
    serviceEndDate: { type: DataTypes.DATEONLY, allowNull: false, field: 'service_end_date' },
    totalServiceDays: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0, field: 'total_service_days' },
    dailyRate: { type: DataTypes.DECIMAL(18, 6), allowNull: false, defaultValue: 0, field: 'daily_rate' },
    recognitionMethod: {
      type: DataTypes.STRING(40),
      allowNull: false,
      defaultValue: 'DAILY_CALENDAR_MONTH',
      field: 'recognition_method',
    },
    postingMode: {
      type: DataTypes.STRING(40),
      allowNull: false,
      defaultValue: 'AUTO_CREATE_DRAFT_JV',
      field: 'posting_mode',
    },
    prepaidAssetAccountId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'prepaid_asset_account_id',
      references: { model: 'chart_of_accounts', key: 'id' },
    },
    expenseAccountId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'expense_account_id',
      references: { model: 'chart_of_accounts', key: 'id' },
    },
    creditAccountId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: 'credit_account_id',
      references: { model: 'chart_of_accounts', key: 'id' },
    },
    costCenterId: { type: DataTypes.INTEGER, allowNull: true, field: 'cost_center_id' },
    departmentId: { type: DataTypes.INTEGER, allowNull: true, field: 'department_id' },
    propertyId: { type: DataTypes.INTEGER, allowNull: true, field: 'property_id' },
    unitId: { type: DataTypes.INTEGER, allowNull: true, field: 'unit_id' },
    projectId: { type: DataTypes.INTEGER, allowNull: true, field: 'project_id' },
    leaseId: { type: DataTypes.INTEGER, allowNull: true, field: 'lease_id' },
    vendorId: { type: DataTypes.INTEGER, allowNull: true, field: 'vendor_id' },
    initialPostingRequired: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: 'initial_posting_required',
    },
    initialPostingStatus: { type: DataTypes.STRING(40), allowNull: true, field: 'initial_posting_status' },
    scheduleStatus: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'NONE', field: 'schedule_status' },
    approvalStatus: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'DRAFT', field: 'approval_status' },
    status: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'DRAFT' },
    recognizedAmount: { type: DataTypes.DECIMAL(18, 2), allowNull: false, defaultValue: 0, field: 'recognized_amount' },
    remainingAmount: { type: DataTypes.DECIMAL(18, 2), allowNull: false, defaultValue: 0, field: 'remaining_amount' },
    suspendedFrom: { type: DataTypes.DATEONLY, allowNull: true, field: 'suspended_from' },
    terminatedOn: { type: DataTypes.DATEONLY, allowNull: true, field: 'terminated_on' },
    terminationReason: { type: DataTypes.TEXT, allowNull: true, field: 'termination_reason' },
    notes: { type: DataTypes.TEXT, allowNull: true },
    isTestData: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false, field: 'is_test_data' },
    createdBy: { type: DataTypes.INTEGER, allowNull: false, field: 'created_by' },
    submittedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'submitted_by' },
    reviewedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'reviewed_by' },
    approvedBy: { type: DataTypes.INTEGER, allowNull: true, field: 'approved_by' },
    deletedAt: { type: DataTypes.DATE, allowNull: true, field: 'deleted_at' },
  },
  {
    tableName: 'prepaid_expenses',
    timestamps: true,
    paranoid: true,
    underscored: true,
    deletedAt: 'deleted_at',
  }
);

module.exports = PrepaidExpense;
