const { AuditLog } = require('../models');

const COMPANY_ENTITY_TYPE = 'company_settings';

const COMPANY_AUDIT_ACTIONS = {
  COMPANY_CREATED: 'COMPANY_CREATED',
  COMPANY_UPDATED: 'COMPANY_UPDATED',
  COMPANY_ACTIVATED: 'COMPANY_ACTIVATED',
  COMPANY_DEACTIVATED: 'COMPANY_DEACTIVATED',
  COMPANY_USER_ASSIGNED: 'COMPANY_USER_ASSIGNED',
  COMPANY_USER_REMOVED: 'COMPANY_USER_REMOVED',
  COMPANY_USER_DEFAULT_CHANGED: 'COMPANY_USER_DEFAULT_CHANGED',
  COMPANY_SWITCHED: 'COMPANY_SWITCHED',
  COMPANY_ACCESS_DENIED: 'COMPANY_ACCESS_DENIED',
  CROSS_COMPANY_ACCESS_BLOCKED: 'CROSS_COMPANY_ACCESS_BLOCKED',
  CROSS_COMPANY_FINANCE_ACCESS_BLOCKED: 'CROSS_COMPANY_FINANCE_ACCESS_BLOCKED',
  FINANCE_MASTER_CREATED: 'FINANCE_MASTER_CREATED',
  FINANCE_MASTER_UPDATED: 'FINANCE_MASTER_UPDATED',
  FINANCE_POSTING_CREATED: 'FINANCE_POSTING_CREATED',
  FINANCE_POSTING_REVERSED: 'FINANCE_POSTING_REVERSED',
  CROSS_COMPANY_FINANCE_POSTING_BLOCKED: 'CROSS_COMPANY_FINANCE_POSTING_BLOCKED',
  INVOICE_POSTED: 'INVOICE_POSTED',
  PAYMENT_POSTED: 'PAYMENT_POSTED',
  PDC_DEPOSIT_POSTED: 'PDC_DEPOSIT_POSTED',
  SECURITY_DEPOSIT_POSTED: 'SECURITY_DEPOSIT_POSTED',
  JV_POSTED: 'JV_POSTED',
  VENDOR_INVOICE_POSTED: 'VENDOR_INVOICE_POSTED',
  PURCHASE_INVOICE_POSTED: 'PURCHASE_INVOICE_POSTED',
  DIRECT_PURCHASE_INVOICE_CREATED: 'DIRECT_PURCHASE_INVOICE_CREATED',
  DIRECT_PURCHASE_INVOICE_UPDATED: 'DIRECT_PURCHASE_INVOICE_UPDATED',
  DIRECT_PURCHASE_INVOICE_POSTED: 'DIRECT_PURCHASE_INVOICE_POSTED',
  DIRECT_PURCHASE_INVOICE_CANCELLED: 'DIRECT_PURCHASE_INVOICE_CANCELLED',
  DIRECT_PURCHASE_INVOICE_PAYMENT_ALLOCATED: 'DIRECT_PURCHASE_INVOICE_PAYMENT_ALLOCATED',
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  SALARY_STRUCTURE_UPDATED: 'SALARY_STRUCTURE_UPDATED',
  LEAVE_POLICY_ASSIGNED: 'LEAVE_POLICY_ASSIGNED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',
  PROMOTION_RECORDED: 'PROMOTION_RECORDED',
  TRANSFER_RECORDED: 'TRANSFER_RECORDED',
  LEAVE_OPENING_BALANCE_APPROVED: 'LEAVE_OPENING_BALANCE_APPROVED',
  LEAVE_APPLICATION_SUBMITTED: 'LEAVE_APPLICATION_SUBMITTED',
  LEAVE_APPLICATION_APPROVED: 'LEAVE_APPLICATION_APPROVED',
  LEAVE_APPLICATION_REJECTED: 'LEAVE_APPLICATION_REJECTED',
  LEAVE_APPLICATION_CANCELLED: 'LEAVE_APPLICATION_CANCELLED',
  ATTENDANCE_LOG_IMPORTED: 'ATTENDANCE_LOG_IMPORTED',
  ATTENDANCE_SUMMARY_GENERATED: 'ATTENDANCE_SUMMARY_GENERATED',
  ATTENDANCE_ADJUSTED: 'ATTENDANCE_ADJUSTED',
  LABOUR_TIMESHEET_SUBMITTED: 'LABOUR_TIMESHEET_SUBMITTED',
  LABOUR_TIMESHEET_APPROVED: 'LABOUR_TIMESHEET_APPROVED',
  OVERTIME_APPROVED: 'OVERTIME_APPROVED',
  ATTENDANCE_PERIOD_GENERATED: 'ATTENDANCE_PERIOD_GENERATED',
  ATTENDANCE_PERIOD_APPROVED: 'ATTENDANCE_PERIOD_APPROVED',
  ATTENDANCE_PERIOD_LOCKED: 'ATTENDANCE_PERIOD_LOCKED',
  PAYROLL_RUN_CREATED: 'PAYROLL_RUN_CREATED',
  PAYROLL_CALCULATED: 'PAYROLL_CALCULATED',
  PAYROLL_APPROVED: 'PAYROLL_APPROVED',
  PAYROLL_LOCKED: 'PAYROLL_LOCKED',
  PAYROLL_REVERSED: 'PAYROLL_REVERSED',
  PAYROLL_ADJUSTMENT_APPROVED: 'PAYROLL_ADJUSTMENT_APPROVED',
  WPS_BATCH_GENERATED: 'WPS_BATCH_GENERATED',
  WPS_BATCH_APPROVED: 'WPS_BATCH_APPROVED',
  WPS_BATCH_EXPORTED: 'WPS_BATCH_EXPORTED',
  WPS_VALIDATION_FAILED: 'WPS_VALIDATION_FAILED',
  COMPLIANCE_EXCEPTION_FOUND: 'COMPLIANCE_EXCEPTION_FOUND',
  EMPLOYEE_SEPARATION_CREATED: 'EMPLOYEE_SEPARATION_CREATED',
  FINAL_SETTLEMENT_GENERATED: 'FINAL_SETTLEMENT_GENERATED',
  FINAL_SETTLEMENT_APPROVED: 'FINAL_SETTLEMENT_APPROVED',
  FINAL_SETTLEMENT_LOCKED: 'FINAL_SETTLEMENT_LOCKED',
  EOS_CALCULATED: 'EOS_CALCULATED',
  LEAVE_ENCASHMENT_CALCULATED: 'LEAVE_ENCASHMENT_CALCULATED',
  PAYROLL_POSTED: 'PAYROLL_POSTED',
  PAYROLL_POSTING_REVERSED: 'PAYROLL_POSTING_REVERSED',
  SETTLEMENT_POSTED: 'SETTLEMENT_POSTED',
  SETTLEMENT_REVERSED: 'SETTLEMENT_REVERSED',
  EMPLOYEE_LEDGER_UPDATED: 'EMPLOYEE_LEDGER_UPDATED',
  PAYROLL_RECONCILIATION_EXCEPTION: 'PAYROLL_RECONCILIATION_EXCEPTION',
  PAYSLIP_GENERATED: 'PAYSLIP_GENERATED',
  PAYSLIP_PUBLISHED: 'PAYSLIP_PUBLISHED',
  PAYSLIP_VOIDED: 'PAYSLIP_VOIDED',
  SALARY_CERTIFICATE_GENERATED: 'SALARY_CERTIFICATE_GENERATED',
  SETTLEMENT_DOCUMENT_GENERATED: 'SETTLEMENT_DOCUMENT_GENERATED',
  PAYROLL_EXPORT_GENERATED: 'PAYROLL_EXPORT_GENERATED',
  BANK_TRANSACTION_POSTED: 'BANK_TRANSACTION_POSTED',
  CROSS_COMPANY_REPORT_ACCESS_BLOCKED: 'CROSS_COMPANY_REPORT_ACCESS_BLOCKED',
  REPORT_GENERATED: 'REPORT_GENERATED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  DASHBOARD_VIEWED: 'DASHBOARD_VIEWED',
  VAT_REPORT_GENERATED: 'VAT_REPORT_GENERATED',
  NUMBER_SERIES_CREATED: 'NUMBER_SERIES_CREATED',
  NUMBER_SERIES_UPDATED: 'NUMBER_SERIES_UPDATED',
  FINANCIAL_YEAR_OPENED: 'FINANCIAL_YEAR_OPENED',
  FINANCIAL_YEAR_CLOSED: 'FINANCIAL_YEAR_CLOSED',
  PERIOD_SOFT_CLOSED: 'PERIOD_SOFT_CLOSED',
  PERIOD_HARD_CLOSED: 'PERIOD_HARD_CLOSED',
  VAT_PERIOD_SUBMITTED: 'VAT_PERIOD_SUBMITTED',
  VAT_PERIOD_LOCKED: 'VAT_PERIOD_LOCKED',
  OPENING_BALANCE_IMPORTED: 'OPENING_BALANCE_IMPORTED',
  SYSTEM_INTEGRITY_SCAN_RUN: 'SYSTEM_INTEGRITY_SCAN_RUN',
  SYSTEM_INTEGRITY_FAILURE: 'SYSTEM_INTEGRITY_FAILURE',
  CROSS_COMPANY_DATA_INTEGRITY_FAILURE: 'CROSS_COMPANY_DATA_INTEGRITY_FAILURE',
  NUMBERING_CONFLICT_FOUND: 'NUMBERING_CONFLICT_FOUND',
  PERIOD_VIOLATION_FOUND: 'PERIOD_VIOLATION_FOUND',
  VAT_PERIOD_VIOLATION: 'VAT_PERIOD_VIOLATION',
  PERMISSION_AUDIT_FAILURE: 'PERMISSION_AUDIT_FAILURE',
};

/**
 * @param {object} params
 * @param {import('express').Request} [params.req]
 * @param {string} params.action
 * @param {number} params.entityId - company_settings.id
 * @param {object} [params.oldValue]
 * @param {object} [params.metadata]
 * @param {number} [params.actorUserId] - when req.user unavailable
 */
async function logCompanyEvent({ req, action, entityId, oldValue = null, metadata = {}, actorUserId }) {
  try {
    const userId = actorUserId ?? req?.user?.id;
    if (!userId) return;

    const companyId = metadata.company_id ?? entityId;
    const newValue = {
      module: 'company_settings',
      company_id: companyId,
      target_company_id: metadata.target_company_id ?? entityId,
      target_user_id: metadata.target_user_id ?? null,
      route: metadata.route ?? req?.originalUrl ?? req?.url ?? null,
      method: metadata.method ?? req?.method ?? null,
      reason: metadata.reason ?? null,
      ...metadata,
    };

    await AuditLog.create({
      entityType: COMPANY_ENTITY_TYPE,
      entityId,
      action,
      oldValue,
      newValue,
      userId,
      ipAddress: req?.ip ?? metadata.ip_address ?? null,
      userAgent: req?.headers?.['user-agent'] ?? metadata.user_agent ?? null,
    });
  } catch (error) {
    console.error('Failed to log company audit entry:', error);
  }
}

module.exports = {
  COMPANY_ENTITY_TYPE,
  COMPANY_AUDIT_ACTIONS,
  logCompanyEvent,
};
