describe('Payroll audit actions', () => {
  test('audit constants registered', () => {
    const { COMPANY_AUDIT_ACTIONS } = require('../../services/companyAuditService');
    expect(COMPANY_AUDIT_ACTIONS.EMPLOYEE_CREATED).toBe('EMPLOYEE_CREATED');
    expect(COMPANY_AUDIT_ACTIONS.EMPLOYEE_UPDATED).toBe('EMPLOYEE_UPDATED');
    expect(COMPANY_AUDIT_ACTIONS.SALARY_STRUCTURE_UPDATED).toBe('SALARY_STRUCTURE_UPDATED');
    expect(COMPANY_AUDIT_ACTIONS.LEAVE_POLICY_ASSIGNED).toBe('LEAVE_POLICY_ASSIGNED');
    expect(COMPANY_AUDIT_ACTIONS.DOCUMENT_UPLOADED).toBe('DOCUMENT_UPLOADED');
    expect(COMPANY_AUDIT_ACTIONS.DOCUMENT_EXPIRED).toBe('DOCUMENT_EXPIRED');
    expect(COMPANY_AUDIT_ACTIONS.PROMOTION_RECORDED).toBe('PROMOTION_RECORDED');
    expect(COMPANY_AUDIT_ACTIONS.TRANSFER_RECORDED).toBe('TRANSFER_RECORDED');
  });
});
